## START: Set by rpmautospec
## (rpmautospec version 0.7.2)
## RPMAUTOSPEC: autorelease, autochangelog
%define autorelease(e:s:pb:n) %{?-p:0.}%{lua:
    release_number = 1;
    base_release_number = tonumber(rpm.expand("%{?-b*}%{!?-b:1}"));
    print(release_number + base_release_number - 1);
}%{?-e:.%{-e*}}%{?-s:.%{-s*}}%{!?-n:%{?dist}}
## END: Set by rpmautospec

Name:           hyprland-protocols
Version:        0.6.4
Release:        0.1
Summary:        Wayland protocol extensions for Hyprland
BuildArch:      noarch

License:        BSD-3-Clause
URL:            https://github.com/hyprwm/hyprland-protocols
Source:         %{url}/archive/v%{version}/%{name}-%{version}.tar.gz

BuildRequires:  meson

%description
%{summary}.

%package        devel
Summary:        Wayland protocol extensions for Hyprland

%description    devel
%{summary}.


%prep
%autosetup -p1


%build
%meson
%meson_build


%install
%meson_install


%files devel
%license LICENSE
%doc README.md
%{_datadir}/pkgconfig/%{name}.pc
%{_datadir}/%{name}/


%changelog
* Mon Apr 07 2025 ploxold - 0.6.4-0.1
- Update to 0.6.4

* Sun Mar 23 2025 ploxold - 0.6.2-0.1
- Update to 0.6.2

* Wed Jan 22 2025 ploxold - 0.6.1-0.1
- Update to 0.6.1

* Fri Jan 17 2025 ploxold - 0.6.0-0.5
- Update to 0.6.0

* Tue Jan 07 2025 ploxold - 0.5.0-0.5
- Update to 0.5.0

## START: Generated by rpmautospec
* Thu Oct 10 2024 Pavel Solovev <daron439@gmail.com> - 0.4.0-1
- Update to 0.4.0

* Mon Jul 22 2024 Pavel Solovev <daron439@gmail.com> - 0.3.0-1
- Update to 0.3.0

* Thu Jul 18 2024 Fedora Release Engineering <releng@fedoraproject.org> - 0.2-5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_41_Mass_Rebuild

* Mon Jun 10 2024 Pavel Solovev <daron439@gmail.com> - 0.2-4
- add the required protocol for hyprland 0.41.1

* Wed Jan 24 2024 Fedora Release Engineering <releng@fedoraproject.org> - 0.2-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_40_Mass_Rebuild

* Sat Jan 20 2024 Fedora Release Engineering <releng@fedoraproject.org> - 0.2-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_40_Mass_Rebuild

* Mon Oct 16 2023 Pavel Solovev <daron439@gmail.com> - 0.2-1
- Initial import (rhbz#2244285)
## END: Generated by rpmautospec